[project]
name = "bigint"
version = "0.1.0"
description = "Big-integer library for C++"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "gcovr>=8.2",
    "pre-commit>=3.5.0",
    "uv>=0.8.24",
]
